//
//  jsonTestFile.swift
//  PD Rebalance
//
//  Created by George Breen on 4/6/21.
//

import Foundation

//
//


let jsonTestData = """
[
    {
        "rank": 1,
        "groupPriority": "Gold",
        "shortDescription": "API RBAC (Regions)",
        "name": "API RBAC (Regions) - commit date June 30.",
        "value": "$",
        "size": 11,
        "duration": 17,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-06-01T04:00:00.000Z",
        "dueDate": "2021-06-30T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 1,
        "afduration": 1,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csweeks": 8,
        "csduration": 14,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 2,
        "groupPriority": "Gold",
        "shortDescription": "Scale Phase 3",
        "name": "Scale Phase 3  - Scale to 100M calls/month.  tied to UK deployment. must be done by July. Michael may be able to delay this by 1/2 months if needed. (additional work outside of S6 team)  - no hard due dates yet",
        "value": "$",
        "comments": "Bryce to check with team to see if this can be August.  Target late July or August - let Michael know so he can plan accordingly.",
        "size": 16,
        "duration": 15,
        "endDate": "2021-09-01T04:00:00.000Z",
        "dueDate": "2021-07-15T04:00:00.000Z",
        "inProgress": "Yes",
        "aaweeks": 4,
        "aaduration": 4,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 6,
        "tsduration": 5,
        "systestweeks": 6,
        "systestduration": 6,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 3,
        "groupPriority": "Gold",
        "shortDescription": "TFLite",
        "name": "TFLite Stateless Extraction - Alex - consolidating platforms.  (Required for Svar3 + UK launch)",
        "value": "E",
        "comments": "see above",
        "size": 12,
        "duration": 10,
        "startDate": "2021-04-01T04:00:00.000Z",
        "endDate": "2021-08-01T04:00:00.000Z",
        "dueDate": "2021-08-01T04:00:00.000Z",
        "aaweeks": 12,
        "aaduration": 10,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 4,
        "groupPriority": "Gold",
        "shortDescription": "SVAR 3 for Pano",
        "name": "SVAR3 for Pano - Amit (TFLite pipeline a pre-requisit for this)",
        "value": "E",
        "size": 8,
        "duration": 7,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-08-01T04:00:00.000Z",
        "dueDate": "2021-07-30T04:00:00.000Z",
        "aaweeks": 8,
        "aaduration": 7,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 5,
        "groupPriority": "Gold",
        "shortDescription": "OrecX Cloud",
        "name": "Genesys PCC Streaming API (Associated) - signed deal, must do by June (or so, no committed date) - at risk based on effort estimate, if needed in June",
        "value": "$",
        "size": 18,
        "duration": 16,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-08-01T04:00:00.000Z",
        "dueDate": "2021-07-30T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 16,
        "tsduration": 14,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 18,
        "extduration": 6,
        "iotduration": 0
    },
    {
        "rank": 6,
        "groupPriority": "Gold",
        "shortDescription": "Prem to clouod migration",
        "name": "Prem to cloud migration tooling - automation for customer instead of manual migration",
        "value": "P",
        "size": 2,
        "duration": 2,
        "endDate": "2021-05-01T04:00:00.000Z",
        "dueDate": "2021-03-31T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afweeks": 2,
        "afduration": 2,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": 7,
        "groupPriority": "Gold",
        "shortDescription": "IoT Speaker Attributes",
        "name": "Speaker Attributes Service for OTT - Amit - Roku ask for age/gender/etc.  Deadline end of March/early April.  Rich says v1 should be done in MArch.  Risk no tester now.  ",
        "value": "C",
        "size": 0,
        "duration": 0,
        "dueDate": "2021-03-31T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 8,
        "groupPriority": "Gold",
        "shortDescription": "SAFE python 2 to 3",
        "name": "SAFE: Python 2 to 3 Migration - on prem only - dev complete, bug fixes to address",
        "value": "E",
        "size": 3,
        "duration": 3,
        "endDate": "2021-05-01T04:00:00.000Z",
        "dueDate": "2021-05-01T04:00:00.000Z",
        "inProgress": "Yes",
        "aaweeks": 2,
        "aaduration": 2,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 9,
        "groupPriority": "Gold",
        "shortDescription": "Python 2 to 3 Migration ",
        "name": "Python 2 to 3 and Python 3 CVE - all",
        "value": "R",
        "size": 84,
        "duration": 71,
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaweeks": 16,
        "aaduration": 14,
        "afweeks": 16,
        "afduration": 12,
        "daweeks": 32,
        "daduration": 27,
        "tsweeks": 12,
        "tsduration": 10,
        "systestweeks": 8,
        "systestduration": 8,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 84,
        "extduration": 28,
        "iotduration": 0
    },
    {
        "rank": 10,
        "groupPriority": "Gold",
        "shortDescription": "Prem accessibility",
        "name": "Prem Accessibility (RBC) - committed to them to finish by December 4, they signed/accepted. Michael notes, need to keep them happy",
        "value": "$",
        "size": 32,
        "duration": 24,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "dueDate": "2021-12-04T05:00:00.000Z",
        "aaduration": 0,
        "afweeks": 32,
        "afduration": 24,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 32,
        "extduration": 11,
        "iotduration": 0
    },
    {
        "rank": 11,
        "groupPriority": "Gold",
        "shortDescription": "RedHat OS Patching",
        "name": "RedHat OS Patching - PD-15323 - needs significant regression testing",
        "value": "R",
        "size": 16,
        "duration": 14,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-07-01T04:00:00.000Z",
        "dueDate": "2021-07-01T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 4,
        "systestduration": 4,
        "resengduration": 0,
        "opsweeks": 12,
        "opsduration": 10,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 12,
        "groupPriority": "Gold",
        "shortDescription": "Mitigating high query counts",
        "name": "Mitigate high query count from the UI (PMR) - caused two outages",
        "value": "R",
        "size": 4,
        "duration": 4,
        "endDate": "2021-05-01T04:00:00.000Z",
        "dueDate": "2021-05-01T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afweeks": 3,
        "afduration": 3,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 13,
        "groupPriority": "Gold",
        "shortDescription": "Org Level Configs",
        "name": "Org level config Call Supervisor (PMR). almost done.  tenant management/separation",
        "value": "C",
        "size": 2,
        "duration": 2,
        "endDate": "2021-05-01T04:00:00.000Z",
        "dueDate": "2021-04-30T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 2,
        "tsduration": 2,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 14,
        "groupPriority": "Gold",
        "shortDescription": "Bandwidth.com Integration",
        "name": "Bandwidth.com Integration (CapOne) - Bryce",
        "value": "C",
        "size": 6,
        "duration": 6,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-07-01T04:00:00.000Z",
        "dueDate": "2021-06-30T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsweeks": 4,
        "opsduration": 4,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 15,
        "groupPriority": "Gold",
        "shortDescription": "BMO Private connection",
        "name": "Private API/UI connections to cloud (BMO) - Bryce - deal blocker. need by Q3.",
        "value": "$",
        "size": 8,
        "duration": 8,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-06-01T04:00:00.000Z",
        "dueDate": "2021-07-30T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 2,
        "afduration": 2,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsweeks": 4,
        "opsduration": 4,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 16,
        "groupPriority": "Gold",
        "shortDescription": "Auto-expire VF",
        "name": "Cloud Voice Feature auto-expiration/purge before 3 years - Bryce - need this for potential legal reasons - Bryce will check with legal to get priority between Green and Gold - may be needed for June",
        "value": "R",
        "comments": "This is an issue with the due date. Bryce to check with legal.",
        "size": 18,
        "duration": 15,
        "startDate": "2021-07-01T04:00:00.000Z",
        "endDate": "2021-09-01T04:00:00.000Z",
        "dueDate": "2021-07-10T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 12,
        "afduration": 9,
        "daweeks": 4,
        "daduration": 4,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 18,
        "extduration": 6,
        "iotduration": 0
    },
    {
        "rank": 17,
        "groupPriority": "Gold",
        "shortDescription": "OrecX Prem",
        "name": "Prem SIPREC (Lloyd's) - Bryce - the need by end of year - takes months of testing - waiting for customer signature",
        "value": "$",
        "comments": "Lloyds probably doesn't need as early as expected.  If they sign and define dates for SIP, then we'll shift as needed.",
        "size": 32,
        "duration": 28,
        "startDate": "2021-08-01T04:00:00.000Z",
        "endDate": "2021-12-01T05:00:00.000Z",
        "dueDate": "2021-09-30T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 24,
        "tsduration": 20,
        "systestweeks": 8,
        "systestduration": 8,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 32,
        "extduration": 11,
        "iotduration": 0
    },
    {
        "rank": 18,
        "groupPriority": "Gold",
        "shortDescription": "UPS",
        "name": "UPS - Universal PIN score - Research driven PIN factor unification.  Pearce agrees.  Contributes to IVR and small effort so Orange",
        "value": "C",
        "comments": "dont drop this",
        "size": 8,
        "duration": 7,
        "startDate": "2021-04-01T04:00:00.000Z",
        "endDate": "2021-06-01T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daweeks": 8,
        "daduration": 7,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "ivrTt": "x"
    },
    {
        "rank": 19,
        "groupPriority": "Gold",
        "shortDescription": "Bulk import",
        "name": "Utilize client-provided information for alerting and investigation (api, ui, bulk import, with csv export)",
        "value": "C",
        "size": 41,
        "duration": 32,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2022-02-01T05:00:00.000Z",
        "aaduration": 0,
        "afweeks": 36,
        "afduration": 27,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 3,
        "systestduration": 3,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x",
        "ivrTt": "x"
    },
    {
        "rank": 20,
        "groupPriority": "Gold",
        "shortDescription": "Avaya Agent",
        "name": "TLS 1.2 Avaya agent on prem (PNC) - Bryce - we need an Avaya lab, part of PNC renewal promised in September. Needs dev work - due September 30",
        "value": "C",
        "size": 10,
        "duration": 9,
        "startDate": "2021-07-01T04:00:00.000Z",
        "endDate": "2021-10-01T04:00:00.000Z",
        "dueDate": "2021-09-30T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 8,
        "tsduration": 7,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 21,
        "groupPriority": "Gold",
        "shortDescription": "AToM Bug Fixes v2",
        "name": "AToM  Regression and Automation - on prem has most issues, so that's first - most critical item discussed",
        "value": "C",
        "size": 30,
        "duration": 26,
        "startDate": "2021-04-01T04:00:00.000Z",
        "endDate": "2021-07-01T04:00:00.000Z",
        "dueDate": "2021-11-30T05:00:00.000Z",
        "aaweeks": 27,
        "aaduration": 23,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 3,
        "systestduration": 3,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 30,
        "extduration": 10,
        "iotduration": 0
    },
    {
        "rank": 22,
        "groupPriority": "Gold",
        "shortDescription": "URLLIB",
        "name": "Urllib3 CVE - PD-16859",
        "value": "R",
        "size": 12,
        "duration": 12,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaweeks": 2,
        "aaduration": 2,
        "afweeks": 2,
        "afduration": 2,
        "daweeks": 2,
        "daduration": 2,
        "tsweeks": 2,
        "tsduration": 2,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extweeks": 12,
        "extduration": 4,
        "iotduration": 0
    },
    {
        "rank": 23,
        "groupPriority": "Gold",
        "shortDescription": "Docker",
        "name": "Docker CVE - PD-10905, CSP-1586",
        "value": "R",
        "size": 2,
        "duration": 2,
        "startDate": "2021-07-01T04:00:00.000Z",
        "endDate": "2021-08-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 2,
        "tsduration": 2,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 2,
        "extduration": 1,
        "iotduration": 0
    },
    {
        "rank": 24,
        "groupPriority": "Gold",
        "shortDescription": "Envoy CVE",
        "name": "Envoy CVE - PD-8567",
        "value": "R",
        "size": 8,
        "duration": 7,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 8,
        "opsduration": 7,
        "csduration": 0,
        "extweeks": 8,
        "extduration": 3,
        "iotduration": 0
    },
    {
        "rank": 25,
        "groupPriority": "Gold",
        "shortDescription": "Docker",
        "name": "Docker/ Linux CVE - CSP-1495",
        "value": "R",
        "size": 0,
        "duration": 0,
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 26,
        "groupPriority": "Gold",
        "shortDescription": "Account Controls",
        "name": "Account Controls - PD-15314, PD-15168",
        "value": "R",
        "size": 1,
        "duration": 1,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2021-10-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 1,
        "opsduration": 1,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 27,
        "groupPriority": "Gold",
        "shortDescription": "Checkmarxx",
        "name": "Checmarx deployed to Cloud - PD-15812",
        "value": "R",
        "size": 0,
        "duration": 0,
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 28,
        "groupPriority": "Gold",
        "shortDescription": "Graph Risk",
        "name": "Graph Risk - Pearce and Shawn say important to IVR TT.  ",
        "value": "C",
        "comments": "dont drop this",
        "size": 8,
        "duration": 7,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-08-01T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daweeks": 8,
        "daduration": 7,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "ivrTt": "x"
    },
    {
        "rank": 29,
        "groupPriority": "Gold",
        "shortDescription": "Call API",
        "name": "Call API beta solution (TIAA) - Bryce - waiting for more data from TIAA if this is orange or blue.  Also needed for IVR.",
        "value": "$",
        "comments": "Lohika start",
        "size": 34,
        "duration": 29,
        "startDate": "2021-08-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 32,
        "tsduration": 27,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 34,
        "extduration": 12,
        "iotduration": 0
    },
    {
        "rank": 30,
        "groupPriority": "Gold",
        "shortDescription": "Account Risk",
        "name": "Account Risk Threshold Change - Lloyds and will need for others too",
        "value": "P",
        "comments": "dont drop this",
        "size": 20,
        "duration": 17,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 4,
        "afduration": 3,
        "daweeks": 16,
        "daduration": 14,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "ivrTt": "x"
    },
    {
        "rank": 31,
        "groupPriority": "Gold",
        "shortDescription": "Genesys Integration (Cloud)",
        "name": "Genesys Integration (Cloud) - blocker for customers - frustration in the field - need a solution for sales - bryce (genesys pure cloud) - unknown due date",
        "value": "$",
        "size": 14,
        "duration": 13,
        "startDate": "2021-08-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 3,
        "tsduration": 3,
        "systestweeks": 3,
        "systestduration": 3,
        "resengduration": 0,
        "opsweeks": 8,
        "opsduration": 7,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 32,
        "groupPriority": "Gold",
        "shortDescription": "Replace BL/WL term",
        "name": "Replace Blacklist/whitelist term - Amit - this term is considered bad in todays time - no customer ask for it - do this year  (only change customer facing elements)",
        "size": 10,
        "duration": 8,
        "startDate": "2021-04-01T04:00:00.000Z",
        "endDate": "2021-07-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afweeks": 10,
        "afduration": 8,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 33,
        "groupPriority": "Gold",
        "shortDescription": "Genesys Agent",
        "name": "Genesys Agent 1.2 (NFCU) - Bryce - overdue - promised in September of 2020! Have not been able to execute on it. they haven't asked.",
        "value": "C",
        "size": 12,
        "duration": 11,
        "startDate": "2021-05-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",

        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 8,
        "tsduration": 7,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 4,
        "opsduration": 4,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 34,
        "groupPriority": "Gold",
        "shortDescription": "Discover Speaker Attributes",
        "name": "Provide audio call and speaker attributes (Discover Post POC) - due date unknown - Churn related (biggest churn reason for discover)",
        "value": "C",
        "size": 12,
        "duration": 11,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-07-01T04:00:00.000Z",
        "aaweeks": 10,
        "aaduration": 9,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": 35,
        "groupPriority": "Green",
        "shortDescription": "AT&T 10Gbps",
        "name": "AT&T 10Gbps turnup - saves us money 90K/mo and OKR, no customer commit, ops resources only",
        "value": "$",
        "size": 2,
        "duration": 2,
        "endDate": "2021-06-01T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 36,
        "groupPriority": "Green",
        "shortDescription": "Token Management Automation",
        "name": "Token Management Automation - causes outages - green trending orange",
        "value": "R",
        "size": 4,
        "duration": 4,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsweeks": 4,
        "opsduration": 4,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 37,
        "groupPriority": "Green",
        "shortDescription": "IAMv2 GA",
        "name": "IAM v2 GA (does not include migration effort from v1 to v2)",
        "value": "C",
        "size": 44,
        "duration": 36,
        "startDate": "2021-04-01T04:00:00.000Z",
        "endDate": "2021-11-01T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 24,
        "afduration": 18,
        "daweeks": 16,
        "daduration": 14,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extweeks": 44,
        "extduration": 15,
        "iotduration": 0
    },
    {
        "rank": 37,
        "groupPriority": "Green",
        "shortDescription": "Amazon Connect",
        "name": "Amazon Connect: Support for complete Passport - ANI Validation, Device and Behavior Authentication",
        "value": "P",
        "size": 5,
        "duration": 5,
        "endDate": "2021-05-01T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 4,
        "tsduration": 4,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 38,
        "groupPriority": "Green",
        "shortDescription": "UK Cloud",
        "name": "UK Cloud - July deadline but Michael can move if needed",
        "value": "$",
        "size": 9.5,
        "duration": 11,
        "startDate": "2021-06-01T04:00:00.000Z",
        "endDate": "2021-10-01T04:00:00.000Z",
        "aaweeks": 0.5,
        "aaduration": 1,
        "afweeks": 0.5,
        "afduration": 1,
        "daweeks": 5,
        "daduration": 5,
        "tsweeks": 0.5,
        "tsduration": 1,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsweeks": 2,
        "opsduration": 2,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 39,
        "groupPriority": "Green",
        "shortDescription": "New Device Ensemble",
        "name": "New Device Ensemble - reduce device confusion (from Research)",
        "comments": "Amit to check",
        "size": 2,
        "duration": 12,
        "startDate": "2021-12-01T05:00:00.000Z",
        "endDate": "2021-09-30T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengweeks": 10,
        "resengduration": 10,
        "opsweeks": 1,
        "opsduration": 1,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 40,
        "groupPriority": "Green",
        "shortDescription": "Account-Centric",
        "name": "Account-centric alerting and investigation - Otherwise this is critical. Need to do this within 6-9 months.",
        "value": "C",
        "size": 37,
        "duration": 29,
        "startDate": "2022-01-01T05:00:00.000Z",
        "endDate": "2022-05-01T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 32,
        "afduration": 24,
        "daweeks": 1,
        "daduration": 1,
        "tsduration": 0,
        "systestweeks": 4,
        "systestduration": 4,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": 41,
        "groupPriority": "Green",
        "shortDescription": "RIFLE",
        "name": "Risk Factor based on LL feat. (RIFLE) - Terry - will be done by research team - not needed for initial UK deployment",
        "value": "C",
        "size": 1,
        "duration": 21,
        "startDate": "2022-01-01T05:00:00.000Z",
        "endDate": "2022-02-01T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daweeks": 1,
        "daduration": 1,
        "tsduration": 0,
        "systestduration": 0,
        "resengweeks": 20,
        "resengduration": 20,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "ivrTt": "x"
    },
    {
        "rank": 0,
        "groupPriority": "Green",
        "shortDescription": "New Auth Ensemble",
        "name": "New Authentication Ensemble - Amit.  better auth rates",
        "comments": "Amit to check into dates.  Need more passport features before 2022",
        "size": 0,
        "duration": 10,
        "startDate": "2021-11-01T04:00:00.000Z",
        "endDate": "2021-11-30T05:00:00.000Z",
        "aaduration": 0,
        "afweeks": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengweeks": 10,
        "resengduration": 10,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 43,
        "groupPriority": "Green",
        "shortDescription": "Voice Mismatch",
        "name": "Voice Mismatch - Amit - helps authentication and risk score.  Mass Mutual asking in Q3 (soft commit)",
        "comments": "Amit to check into dates",
        "size": 13,
        "duration": 10,
        "startDate": "2021-08-01T04:00:00.000Z",
        "endDate": "2021-09-30T04:00:00.000Z",
        "aaweeks": 9,
        "aaduration": 8,
        "afweeks": 2,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 44,
        "groupPriority": "Green",
        "shortDescription": "Consistent monitoring",
        "name": "Consistent monitoring and alerting - Chris D - ops task - also in Efficiency TT",
        "value": "R",
        "size": 14,
        "duration": 13,
        "startDate": "2021-09-01T04:00:00.000Z",
        "endDate": "2022-03-01T05:00:00.000Z",
        "aaweeks": 2,
        "aaduration": 2,
        "afweeks": 4,
        "afduration": 3,
        "daweeks": 4,
        "daduration": 4,
        "tsweeks": 4,
        "tsduration": 4,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 45,
        "groupPriority": "Green",
        "shortDescription": "Fraud tagging",
        "name": "Fraud Tagging - Shawn says this is most requested item from 20 customers. want to tag fraud with info, not notes field and reportability. also on churn TT (subset)",
        "value": "C",
        "size": 12,
        "duration": 10,
        "startDate": "2022-03-01T05:00:00.000Z",
        "endDate": "2022-05-01T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 10,
        "afduration": 8,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": 46,
        "groupPriority": "Green",
        "shortDescription": "Refresh Avaya",
        "name": "Refresh Avaya Extension PD-9497 - highest Jira for Julien.",
        "value": "C",
        "size": 5,
        "duration": 5,
        "startDate": "2021-11-01T04:00:00.000Z",
        "endDate": "2021-12-01T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 4,
        "tsduration": 4,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 47,
        "groupPriority": "Green",
        "shortDescription": "GUFF Refactor",
        "name": "GUFF File updates (Verizon) - can't accurately invoice - need to update billing file (doing manual now) - need for SOX too.",
        "value": "$",
        "size": 1,
        "duration": 1,
        "startDate": "2021-11-01T04:00:00.000Z",
        "endDate": "2022-01-01T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 6,
        "extduration": 2,
        "iotduration": 0
    },
    {
        "rank": 48,
        "groupPriority": "Green",
        "shortDescription": "Automatic Backcoloring",
        "name": "Automatic Backcoloring - Shawn says popular with clients. automates copy/paste and manual info moving. Gives Pindrop more credit for fraud finding.",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": 49,
        "groupPriority": "Green",
        "shortDescription": "STIR/SHAKEN",
        "name": "STIR/SHAKEN - Bryce. competitive concern.  Discuss with NextCaller to injest this",
        "value": "P",
        "size": 11,
        "duration": 9,
        "startDate": "2022-01-01T05:00:00.000Z",
        "endDate": "2022-04-01T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 8,
        "afduration": 6,
        "daduration": 0,
        "tsweeks": 2,
        "tsduration": 2,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": 50,
        "groupPriority": "Green",
        "shortDescription": "Cloud Accessibility",
        "name": "Cloud Accessibility (BMO) - Bryce - ton of work, some outsourcing, they need by June 2022",
        "value": "$",
        "size": 16,
        "duration": 12,
        "startDate": "2021-11-01T04:00:00.000Z",
        "endDate": "2021-03-01T05:00:00.000Z",
        "dueDate": "2022-06-30T04:00:00.000Z",
        "aaduration": 0,
        "afweeks": 16,
        "afduration": 12,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 16,
        "extduration": 6,
        "iotduration": 0
    },
    {
        "rank": 60,
        "groupPriority": "Green",
        "shortDescription": "IAMv2 Migration",
        "name": "IAM v1 to v2 customer migration ",
        "size": 12,
        "duration": 10,
        "aaduration": 0,
        "afweeks": 8,
        "afduration": 6,
        "daweeks": 4,
        "daduration": 4,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "shortDescription": "On-Prem Boost",
        "name": "Phase 1 - BOOST (and beyond Boost) - Create framework for delivering new features to on-premise customers - see architecture milestone on the right - depends on planning, what we can implement",
        "value": "C",
        "comments": "need to scope with Sachin/Yvette - customer input and define how to staff",
        "size": 64,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "shortDescription": "Kube Upgrade",
        "name": "Kube Upgrade and CVE - PD-15042 (Migrate services/deployments to new Architecture/cluster - AA, AF services already covered as part of S6 team and project)",
        "value": "R",
        "size": 14,
        "duration": 12,
        "startDate": "2021-08-01T04:00:00.000Z",
        "endDate": "2021-09-01T04:00:00.000Z",
        "dueDate": "2021-12-23T05:00:00.000Z",
        "aaduration": 0,
        "afduration": 0,
        "daweeks": 12,
        "daduration": 10,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "name": "Native Micdrop improvements (bug related) -- Bryce - clean and reduce cost. customer complaints. completed and deployed",
        "value": "C",
        "size": 1,
        "duration": 1,
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsweeks": 1,
        "tsduration": 1,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "shortDescription": "SKT",
        "name": "SKT (South Korea) -  - will contract in Q2, want install end of q3) - Iot",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "name": "Next Gen Strategic Architecture (design/plan) - must help on prem customers as orange.  High priority if we are going to unify platforms, otherwise whatever on-prem path is orange",
        "value": "C",
        "size": 0,
        "duration": 0,
        "startDate": "2021-03-01T05:00:00.000Z",
        "endDate": "2021-06-01T04:00:00.000Z",
        "comments": "ongoing planning of phases ",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "shortDescription": "TiVo",
        "name": "TiVo Production Readiness - early Q3 Tivo deadline",
        "value": "$",
        "size": 0,
        "duration": 0,
        "dueDate": "2021-08-31T04:00:00.000Z",
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "rank": -1,
        "groupPriority": "Gold",
        "name": "Improving AToM Stability and Monitoring - Completed",
        "value": "C",
        "size": 2,
        "duration": 2,
        "aaweeks": 2,
        "aaduration": 2,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Green",
        "name": "Fraud Feedback Data Import - Pearce notes need for iVR TT. one of top TT asks. doing manual now.",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x",
        "ivrTt": "x"
    },
    {
        "groupPriority": "Green",
        "name": "Short-lived API tokens (Santander) - will accept a 12 month exception - Pearce - recent ask from Santander - must do within 12 months of implementation - around late Q2",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Artifactory On-Prem",
        "name": "Artifactory for On Prem Upgrades - Jimmy says for CS savings.",
        "size": 4,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extweeks": 4,
        "extduration": 2,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "IVR Reporting",
        "name": "IVR reporting of right data fields for us and customer",
        "value": "P",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "IVR Testing",
        "name": "IVR automation and regression testing",
        "value": "P",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Link Analysis",
        "name": "Provide additional link analysis for fraud investigation  - fraud tagging (left) is a subset of this.",
        "value": "C",
        "size": 32,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "churnTt": "x"
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "GDPR",
        "name": "Cloud GDPR Phase 1 - needed for UK readiness.  M/L remaining.",
        "value": "R",
        "size": 16,
        "duration": 0,
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Waterdrop to Iris",
        "name": "Waterdrop to Iris conversion - tech debt - consistent  UI across platform.",
        "value": "E",
        "size": 16,
        "duration": 0,
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Call Manager",
        "name": "Call Manager - Signaling manager for all capture sources - need to modernize all inconsistent capture sources",
        "value": "E",
        "size": 8,
        "duration": 0,
        "inProgress": "Yes",
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Ternary Caller ID",
        "name": "Ternary Caller ID Status and V2 Caller ID API.  Amit - critical but no commit.  can we use NextCaller?  Pink if we can get it as a risk reason",
        "value": "P",
        "size": 8,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Post delivery Passport Tenant Cleanup PD-6022. Himanshu - too much manual work for Passport customers.  Julien to check scripting workaround for now.",
        "value": "E",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Boost Passport enrollment & auth rates using ANI on file and low risk auth - Amit - ",
        "size": 4,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Uno Appliance Deployment Issues - Bryce - lots of issues - eg. no HA - can't do upgrades, need to fix - could be green or orange - Bryce to check if this is really going to be used - can we make it pink?",
        "value": "C",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "ROI Dashboard",
        "name": "Passport ROI Dashboard - amit",
        "size": 32,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Reduce the Cost Per Call by 35% - various items in here. can do 22% without ENG.  Scale items (22%) is already covered on left.",
        "value": "$",
        "size": 32,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "ID-less Authentication",
        "name": "ID Less Authentication - Amit - allows us to match call to our unique ID",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Increase Capacity for Pcap Broker OnPrem - Diego says with is for Wells Fargo. causing outages. Pink now but could be critical.  Reasses in 2 months to see if hardware refresh increases performance.  Could contractor do this?  Action - let's check into this asap.",
        "value": "R",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Deep Phoneprinting ",
        "name": "Deep Phoneprinting (can be orange if Discover accepts POC) - amit",
        "size": 0,
        "duration": 7,
        "aaweeks": 4,
        "aaduration": 4,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 3,
        "systestduration": 3,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "name": "Deploy Well Architected (Amazon Partnership) - Bryce to check with ChrisD if this is done",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "GA support for API & UI over VPN or Private Connection ",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Automatic TTC Installation and UNO appliance - Diego - tap to cloud is more important.  Bryce thinks uplife isnt that bad - just makes inconsistent installations.  Can live with.",
        "value": "E",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Call Phase in RTES on prem (Jackson) - Pearce - no one using this.  Jackson hasn't brought up again",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Call Phase in CSV prem (Jackson) - Pearce - might get bumped to pink if they bring it up",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Cloud Localization (France Cloud) - Michael wants to discuss a proactive approach to see if we can partner",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Old Mutual (South Africa) - Start in UK - Pano - was dependent on amazon setting up in south africa - watch this to follow amazon",
        "value": "$",
        "size":0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Sprinklr (India/HDFC) - IoT - unless we can go into their private cloud, we can't win this - need to do strategy of non-Amazon local clouds - George to discuss this as a part of architecture review.  PEr vijay - consider support in this.",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Citi Cloud Audit Log Export -will be blocker if they move to cloud.  blue until they decide a date.",
        "value": "$",
        "size": 0,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Blue",
        "name": "Sonae Protect Cloud Agent (EMEA Cloud) - portugese customer - covid issues there, waiting for them to come back",
        "value": "$",
        "size": 32,
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "shortDescription": "PRS Refactor",
        "name": "PRS Refactor",
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Gold",
        "shortDescription": "Tableau Fixes",
        "name": "Tableau Reporting Refactor",
        "duration": 15,
        "aaduration": 0,
        "afweeks": 3,
        "afduration": 3,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 5,
        "systestduration": 5,
        "resengduration": 0,
        "opsweeks": 8,
        "opsduration": 7,
        "csduration": 0,
        "extweeks": 5,
        "extduration": 2,
        "iotduration": 0
    },
    {
        "name": "Account Anomaly Detection - top priority for IVR",
        "duration": 0,
        "aaduration": 0,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestduration": 0,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0,
        "ivrTt": "x"
    },
    {
        "groupPriority": "Gold",
        "shortDescription": "Accounts Report",
        "name": "Accounts report for automated reports",
        "duration": 12,
        "afweeks": 8,
        "afduration": 6,
        "daweeks": 4,
        "daduration": 4,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "Dark Mode",
        "name": "Dark Mode - Needed for Deep Phoneprinting",
        "duration": 9,
        "aaweeks": 6,
        "aaduration": 5,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsweeks": 3,
        "opsduration": 3,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "groupPriority": "Pink",
        "shortDescription": "TFLite Prediction",
        "name": "TFLite Prediction",
        "duration": 8,
        "aaweeks": 8,
        "aaduration": 7,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 1,
        "systestduration": 1,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "shortDescription": "AToM Refactoring",
        "name": "AToM Refactoring - Needs Python 2 to 3 testing in place first",
        "duration": 12,
        "aaweeks": 12,
        "aaduration": 10,
        "afduration": 0,
        "daduration": 0,
        "tsduration": 0,
        "systestweeks": 2,
        "systestduration": 2,
        "resengduration": 0,
        "opsduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "shortDescription": "NextCaller - Fraud Intel",
        "name": "Next Caller Integration for Fraud intelligence",
        "resengduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "shortDescription": "NextCaller - Platform",
        "name": "Next Caller Platform Integration",
        "resengduration": 0,
        "csduration": 0,
        "extduration": 0,
        "iotduration": 0
    },
    {
        "name": "Arista Upgrade",
        "opsduration": 12
    },
    {
        "groupPriority": "Pink",
        "name": "AToM APT batch for cloud - currently creating phoneprints in cloud is a manual process by research",
        "comments": "PD-8549"
    },
    {
        "name": "Zenkey Integration (or similar) - Automated step up/OTP feature in product",
        "comments": "due end April 2022"
    },
    {
        "name": "Enhanced UI search experience"
    }
]
"""
